services:
  day20-api:
    restart: unless-stopped
    build: ./backend
    container_name: day20-elysia
    expose:
      - "3000"
    ports:
      - "3250:3250"
    env_file:
      - ./backend/.env
    environment:
      - BUN_ENV=production
    networks:
      - day20-network

  day20-ui:
    restart: unless-stopped
    build: ./frontend
    container_name: day20-vue
    ports:
      - "3500:3500"
    expose:
      - "3251"
    networks:
      - day20-network

  day20-nginx-exporter:
    restart: unless-stopped
    image: nginx/nginx-prometheus-exporter:1.4
    container_name: day20-nginx-exporter
    command:
      - --nginx.scrape-uri=http://day20-vue:3251/stub_status
    ports:
      - "3251:9113"
    depends_on:
      - day20-ui
    networks:
      - day20-network

networks:
  day20-network:
    driver: bridge
